from .base import *

SECRET_KEY = os.environ['SECRET_KEY']
DEBUG = False
ADMINS = (
    ('Admin', os.environ['Admin'])
)
SERVER_EMAIL = os.environ['SERVER_EMAIL']
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_PORT = os.environ['EMAIL_PORT']
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
EMAIL_USE_TLS = os.environ['EMAIL_USE_TLS']
ALLOWD_HOSTS = os.environ['ALLOWD_HOSTS']

if not DEBUG:
    import django_heroku
    django_heroku.settings(locals())

# 共通設定
BASE_DIR
INSTALLED_APPS
AUTH_USER_MODEL
MIDDLEWARE
ROOT_URLCONF
TEMPLATES
WSGI_APPLICATION
AUTH_PASSWORD_VALIDATORS
LANGUAGE_CODE
TIME_ZONE
USE_I18N
USE_L10N
USE_TZ
STATIC_URL
STATICFILES_DIRS
ACTIVATION_TIMEOUT_SECONDS
LOGIN_URL
LOGIN_REDIRECT_URL
LOGOUT_REDIRECT_URL
LOGGING
